#!/bin/sh
set -ue

xcode-select --install
read -p 'A window that lets you install XCode CLI tools should have opened.
If you'\''ve closed it, run `xcode-select --install` to reopen it.
Please install the XCode CLI tools and then press enter.' quark1

[ `arch` = arm64 ] && {
        echo "Detected an ARM CPU, installing Rosetta..."
        sudo softwareupdate --install-rosetta
        read -p 'A window that lets you install Rosetta should have opened.
If you'\''ve closed it, run `sudo softwareupdate --install-rosetta` to reopen it.
Please install the Rosetta and then press enter.' quark2
}

echo "You need to agree to the XCode license first."
sudo xcodebuild -license

echo "Installing pixelcmtd/tools..."
curl -L https://github.com/pixelcmtd/tools/raw/master/bootstrap | sh

echo "Installing pixelcmtd/CMMSS..."
cd
git clone https://github.com/pixelcmtd/CMMSS.git
cd CMMSS
./install.sh
