#!/bin/sh
set -ue

read -p 'To improve your experience, we will assume that you agree to all Apple SLAs.
To agree, press enter. To disagree, press ctrl-c.' quark2

xcode-select --install && \
read -p 'A window that lets you install XCode CLI tools should have opened.
If you'\''ve closed it, run `xcode-select --install` to reopen it.
Please install the XCode CLI tools and then press enter.' quark1 || true

[ `arch` = arm64 ] && {
        echo "Detected an ARM CPU, installing Rosetta..."
        echo A | sudo softwareupdate --install-rosetta
}

echo '                                         agree' | sudo xcodebuild -license

echo "Installing pixelcmtd/tools..."
curl -L https://github.com/pixelcmtd/tools/raw/master/bootstrap | sh

echo "Installing pixelcmtd/CMMSS..."
cd
git clone https://github.com/pixelcmtd/CMMSS.git
cd CMMSS
./install.sh
